package com.lyj.etprotal.dao;

import com.lyj.etprotal.entity.SysUser;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbg.generated
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbg.generated
     */
    int insertSelective(SysUser record);
}