package com.lyj.etprotal.entity;

public class SysUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.pass
     *
     * @mbg.generated
     */
    private String pass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.mobile
     *
     * @mbg.generated
     */
    private Integer mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.create_user_id
     *
     * @mbg.generated
     */
    private Integer create_user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.create_time
     *
     * @mbg.generated
     */
    private String create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sys_user.dept_id
     *
     * @mbg.generated
     */
    private Integer dept_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.id
     *
     * @return the value of tb_sys_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.id
     *
     * @param id the value for tb_sys_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.name
     *
     * @return the value of tb_sys_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.name
     *
     * @param name the value for tb_sys_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.pass
     *
     * @return the value of tb_sys_user.pass
     *
     * @mbg.generated
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.pass
     *
     * @param pass the value for tb_sys_user.pass
     *
     * @mbg.generated
     */
    public void setPass(String pass) {
        this.pass = pass == null ? null : pass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.email
     *
     * @return the value of tb_sys_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.email
     *
     * @param email the value for tb_sys_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.mobile
     *
     * @return the value of tb_sys_user.mobile
     *
     * @mbg.generated
     */
    public Integer getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.mobile
     *
     * @param mobile the value for tb_sys_user.mobile
     *
     * @mbg.generated
     */
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.status
     *
     * @return the value of tb_sys_user.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.status
     *
     * @param status the value for tb_sys_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.create_user_id
     *
     * @return the value of tb_sys_user.create_user_id
     *
     * @mbg.generated
     */
    public Integer getCreate_user_id() {
        return create_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.create_user_id
     *
     * @param create_user_id the value for tb_sys_user.create_user_id
     *
     * @mbg.generated
     */
    public void setCreate_user_id(Integer create_user_id) {
        this.create_user_id = create_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.create_time
     *
     * @return the value of tb_sys_user.create_time
     *
     * @mbg.generated
     */
    public String getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.create_time
     *
     * @param create_time the value for tb_sys_user.create_time
     *
     * @mbg.generated
     */
    public void setCreate_time(String create_time) {
        this.create_time = create_time == null ? null : create_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_user.dept_id
     *
     * @return the value of tb_sys_user.dept_id
     *
     * @mbg.generated
     */
    public Integer getDept_id() {
        return dept_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_user.dept_id
     *
     * @param dept_id the value for tb_sys_user.dept_id
     *
     * @mbg.generated
     */
    public void setDept_id(Integer dept_id) {
        this.dept_id = dept_id;
    }
}